[sources]
unknown-registry = "deny"
# unknown-git = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Unicode-3.0",
]

[licenses.private]
ignore = true
